apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ke3hix87g-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ke3hix87g-dotnet-basic-gitops