apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ke3hix87g-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-a9a99c5e1d.0r12.p3.openshiftapps.com/rhtap/rhtap-qe-dotnet-basic:2b37d7d58ec065abb6121e6256315a7f59020e5b@sha256:f9549bfb1af0528aee1883da4714d2734ec56aa17ee215901cad6cf66cb702c3
          name: container-image
